export const dailyTips = [
  'Pensez à sauvegarder vos fiches de révision régulièrement !',
  "Utilisez des moyens mnémotechniques pour mémoriser plus facilement les mécanismes d'action.",
  "L'IA est comme un stagiaire motivé : guidez-la avec des instructions précises.",
  'Pour de meilleurs résultats, convertissez vos PDFs en texte avant de les analyser.',
  "Demandez à l'IA de critiquer et d'améliorer ses propres réponses pour une qualité optimale.",
  "La règle 80/20 : demandez les 20% de connaissances qui répondent à 80% des questions d'examen.",
  "Structurez vos fiches 'pour un étudiant avec TDAH' pour améliorer la clarté et la concision.",
  "N'hésitez pas à itérer : la première réponse de l'IA n'est jamais la meilleure.",
  'Vérifiez toujours les posologies et interactions avec des sources officielles avant toute application clinique.',
  "Créez une bibliothèque de prompts personnalisés dans 'Mon Carnet' pour gagner du temps sur vos tâches récurrentes.",
  'Placez vos instructions les plus importantes au début et à la fin de vos prompts longs.',
  "Utilisez la technique du 'pas à pas' pour les calculs pharmacologiques complexes.",
  'Pour les sujets importants, posez la même question à plusieurs reprises pour valider la cohérence des réponses.',
  'Testez toujours vos prompts sur plusieurs exemples avant de les considérer comme fiables.',
  'Utilisez des délimiteurs clairs (triples guillemets) pour séparer vos instructions du contexte.',
  'Spécifiez toujours le format de sortie attendu (Markdown, tableau, JSON) pour éviter les surprises.',
  "Privilégiez les instructions positives ('faites ceci') plutôt que négatives ('ne faites pas cela').",
  "Constituez-vous un jeu de test personnel pour valider l'efficacité de vos prompts.",
  "Utilisez des personas précises (ex: 'pharmacien hospitalier en oncologie') pour obtenir des réponses plus expertes.",
  'Pour les documents longs, placez les instructions cruciales au début et à la fin du prompt.',
];
